// AUTO-GENERATED BY onyx-gen. DO NOT EDIT.

export interface AuditLog {
  action?: string;
  actorId: string | null;
  changes: any | null;
  dateTime?: Date;
  errorCode: string | null;
  errorMessage: string | null;
  id?: string;
  metadata: any | null;
  requestId: string | null;
  resource: string | null;
  status: string | null;
  targetId: string | null;
  tenantId: string | null;
  [key: string]: any;
}

export interface Permission {
  createdAt?: Date;
  deletedAt: Date | null;
  description: string | null;
  id?: string;
  name?: string;
  updatedAt?: Date;
  [key: string]: any;
}

export interface Role {
  createdAt?: Date;
  deletedAt: Date | null;
  description: string | null;
  id?: string;
  isSystem?: boolean;
  name?: string;
  updatedAt?: Date;
  [key: string]: any;
}

export interface RolePermission {
  createdAt?: Date;
  id?: string;
  permissionId?: string;
  roleId?: string;
  [key: string]: any;
}

export interface User {
  createdAt?: Date;
  deletedAt: Date | null;
  email?: string;
  id?: string;
  isActive?: boolean;
  lastLoginAt: Date | null;
  updatedAt?: Date;
  username?: string;
  [key: string]: any;
}

export interface UserProfile {
  address: any | null;
  age: number | null;
  avatarUrl: string | null;
  bio: string | null;
  createdAt?: Date;
  deletedAt: Date | null;
  firstName?: string;
  id?: string;
  lastName?: string;
  phone: string | null;
  updatedAt: Date | null;
  userId?: string;
  [key: string]: any;
}

export interface UserRole {
  createdAt?: Date;
  id?: string;
  roleId?: string;
  userId?: string;
  [key: string]: any;
}

export type OnyxSchema = {
  AuditLog: AuditLog;
  Permission: Permission;
  Role: Role;
  RolePermission: RolePermission;
  User: User;
  UserProfile: UserProfile;
  UserRole: UserRole;
};

export type Schema = OnyxSchema;
export const Schema = {} as OnyxSchema;

export enum tables {
  AuditLog = "AuditLog",
  Permission = "Permission",
  Role = "Role",
  RolePermission = "RolePermission",
  User = "User",
  UserProfile = "UserProfile",
  UserRole = "UserRole",
}

