// AUTO-GENERATED BY onyx-gen. DO NOT EDIT.
// Generated at 2025-09-04T18:26:41.310Z

export interface User {
  id?: string;
  username?: string;
  email?: string;
  isActive?: boolean;
  lastLoginAt: Date | null;
  createdAt?: Date;
  updatedAt?: Date;
  deletedAt: Date | null;
  [key: string]: any;
}

export interface UserProfile {
  id?: string;
  userId?: string;
  firstName?: string;
  lastName?: string;
  phone: string | null;
  address: any | null;
  avatarUrl: string | null;
  bio: string | null;
  createdAt?: Date;
  updatedAt: Date | null;
  deletedAt: Date | null;
  age: number | null;
  [key: string]: any;
}

export interface Role {
  id?: string;
  name?: string;
  description: string | null;
  isSystem?: boolean;
  createdAt?: Date;
  updatedAt?: Date;
  deletedAt: Date | null;
  [key: string]: any;
}

export interface Permission {
  id?: string;
  name?: string;
  description: string | null;
  createdAt?: Date;
  updatedAt?: Date;
  deletedAt: Date | null;
  [key: string]: any;
}

export interface UserRole {
  id?: string;
  userId?: string;
  roleId?: string;
  createdAt?: Date;
  [key: string]: any;
}

export interface RolePermission {
  id?: string;
  roleId?: string;
  permissionId?: string;
  createdAt?: Date;
  [key: string]: any;
}

export type OnyxSchema = {
  User: User;
  UserProfile: UserProfile;
  Role: Role;
  Permission: Permission;
  UserRole: UserRole;
  RolePermission: RolePermission;
};

export type Schema = OnyxSchema;
export const Schema = {} as OnyxSchema;

export enum tables {
  User = "User",
  UserProfile = "UserProfile",
  Role = "Role",
  Permission = "Permission",
  UserRole = "UserRole",
  RolePermission = "RolePermission",
}

